### ISSUE TITLE
`link` fails silently if directory doesn't exist

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#6] opened 2019-07-29 18:59 UTC
If you link to a directory that doesn't exist, then it fails silently. There's no indication that if failed.

Proposed solution:

 - If it doesn't like, print the error
 - If it does link, print something like `Linking <package-name> done.`

**Comment by hugomrdias** [comment] 2019-07-30 10:08
fixed in master

**Comment by vmx** [comment] 2019-07-30 10:47
I don't have permission to re-open this issue, but I would.

Using master:

```console
$ /home/vmx/src/pl/misc/connect-deps/cli.js link ../thisdoesntexist
✔ Linking ../thisdoesntexist
```

No `.connect-deps.json` file is created (which is correct), but it should display a failure and not success.

**Comment by hugomrdias** [comment] 2019-07-30 14:23
```shell
❯ ../../connect-deps/cli.js link ../dddd                        
✖ Error: can't find /Users/hugomrdias/code/pl/dddd
```

can't reproduce this

**Comment by vmx** [comment] 2019-07-30 14:40
I found the problem, it was on my environment. I had a `package.json` in `/tmp`. So the `read-pkg-up` package picked up that file. I think it would make sense to use `read-pkg` instead, as you really want that specific module and not some random one higher up in your file hierarchy.

**Closed as completed** 2019-07-30 14:54 UTC
